# Generated by Django 5.2.4 on 2025-08-30 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicleservice",
            options={
                "ordering": ["-service_date"],
                "verbose_name": "Vehicle Service",
                "verbose_name_plural": "Vehicle Services",
            },
        ),
        migrations.RenameField(
            model_name="vehicleservice",
            old_name="date",
            new_name="service_date",
        ),
        migrations.AddField(
            model_name="vehicleservice",
            name="garage_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vehicleservice",
            name="mileage",
            field=models.PositiveIntegerField(
                blank=True, help_text="Vehicle mileage at time of service", null=True
            ),
        ),
        migrations.AddField(
            model_name="vehicleservice",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("maintenance", "Regular Maintenance"),
                    ("repair", "Repair"),
                    ("inspection", "Inspection"),
                    ("oil_change", "Oil Change"),
                    ("tire_change", "Tire Change"),
                    ("other", "Other"),
                ],
                default="maintenance",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vehicleservice",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="vehicle.vehicle",
            ),
        ),
        migrations.CreateModel(
            name="VehicleServiceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.FileField(upload_to="vehicle_service_docs/")),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="vehicle.vehicleservice",
                    ),
                ),
            ],
        ),
    ]
