# Generated by Django 5.2.4 on 2025-08-30 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0002_alter_vehicleservice_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Garage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Garage",
                "verbose_name_plural": "Garages",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="vehicleservice",
            name="garage_name",
        ),
        migrations.AddField(
            model_name="vehicleservice",
            name="garage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="vehicle.garage",
            ),
        ),
    ]
