# Generated by Django 5.2.4 on 2025-07-26 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("LKR", "Sri Lankan Rupee"),
                            ("EUR", "Euro"),
                            ("AUD", "Australian Dollar"),
                        ],
                        default="LKR",
                        max_length=6,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Salary", "Salary"),
                            ("Bonus", "Bonus"),
                            ("Other", "Other"),
                        ],
                        default="Salary",
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("basic_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "allowance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "stamp_duty",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "epf_user",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "other_deductions",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "take_home",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "epf_employer",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "etf_employer",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="income.source"
                    ),
                ),
            ],
        ),
    ]
