# Generated by Django 5.2.4 on 2025-07-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="is_tax_paid",
            field=models.BooleanField(default=True),
        ),
    ]
