# Generated by Django 5.2.4 on 2025-07-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0002_income_is_tax_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="is_template",
            field=models.BooleanField(default=False),
        ),
    ]
