# Generated by Django 5.2.4 on 2025-08-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0003_income_is_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
