# Generated by Django 5.2.4 on 2025-08-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0004_alter_income_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="income",
            options={"verbose_name_plural": "Incomes"},
        ),
        migrations.AddField(
            model_name="income",
            name="exchange_rate_lkr",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
