# Generated by Django 5.2.4 on 2025-08-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0005_alter_income_options_income_exchange_rate_lkr"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="is_allowance_for_funds",
            field=models.BooleanField(default=False),
        ),
    ]
